- name: Cluster Node
  hosts: cluster_nodes
  tasks:
   - name: apt update
     ansible.builtin.apt:
       name: "*"
       state: latest
       update_cache: true
   - name: apt upgrade
     ansible.builtin.apt:
       state: latest
       update_cache: false
       upgrade: safe
   - name: remove /etc/hosts localhost hostname
     ansible.builtin.lineinfile:
       path: /etc/hosts
       regex: '^127.0.1.1.*'
       state: absent
   - name: remove /etc/hosts comments
     ansible.builtin.lineinfile:
       path: /etc/hosts
       regex: '^#.*'
       state: absent
   - name: update /etc/hosts with peers
     ansible.builtin.lineinfile:
       path: /etc/hosts
       line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_hostname }}.local"
     with_items: "{{ ansible_play_batch }}"
   - name: apt install iptables
     ansible.builtin.apt:
       name: iptables
       state: present
   - name: apt install nfs-common
     ansible.builtin.apt:
       name: nfs-common
       state: present