- name: Kubernetes Monitoring
  hosts: kubernetes_control_nodes
  tasks:
    - name: add prometheus repository to helm
      kubernetes.core.helm_repository:
        name: prometheus
        repo_url: https://prometheus-community.github.io/helm-charts
    - name: deploy kube-prometheus-stack to monitoring namespace
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          alertmanager:
            service:
              type: LoadBalancer
              loadBalancerIp: 198.168.1.172
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          prometheus:
            service:
              type: LoadBalancer
              loadBalancerIP: 198.168.1.173
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 100Gi      
          grafana:
            service:
              type: LoadBalancer
              loadBalancerIP: 192.168.1.174
    - name: patch prometheus to use metallb dedicated ip address
      ansible.builtin.shell: |
        kubectl patch service prometheus-kube-prometheus-prometheus --namespace monitoring --patch '{ "spec": { "type": "LoadBalancer", "loadBalancerIP": "192.168.1.173" } }' > /tmp/prometheus.log
        exit 0
      args:
        creates: /tmp/prometheus.log
