- name: Kubernetes Monitoring
  hosts: kubernetes_control_nodes
  tasks:
    - name: add prometheus repository to helm
      kubernetes.core.helm_repository:
        name: prometheus
        repo_url: https://prometheus-community.github.io/helm-charts
    - name: deploy kube-prometheus-stack to monitoring namespace
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          prometheusOperator:
            service:
              type: LoadBalancer
              loadBalancerIP: 198.168.1.175
          prometheus:
            service:
              type: LoadBalancer
              loadBalancerIP: 198.168.1.176
            thanosService:
              enabled: true
            thanosServiceMonitor:
              enabled: true
            thanosServiceExternal:
              enabled: true
              loadBalancerIP: 198.168.1.177
            prometheusSpec:
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 100Gi      
          alertmanager:
            service:
              type: LoadBalancer
              loadBalancerIp: 198.168.1.178
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          thanosRuler:
            enabled: true
            service:
              type: LoadBalancer
              loadBalancerIP: 198.168.1.179
            thanosRulerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi              
                  

              