- name: Kubernetes Master
  hosts: kubernetes_control_nodes
  tasks:
    - name: install k3s
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable servicelb --token myrandompassword --node-ip {{ ansible_host }} --disable-cloud-controller --disable local-storage >> /tmp/k3s.log
        exit 0
      args:
        creates: /tmp/k3s.log
    - name: apt install git
      ansible.builtin.apt:
        name: git
        state: present
    - name: create .profile
      ansible.builtin.file:
        path: /root/.profile
        owner: root
        group: root
        mode: u+rw
    - name: add config view to ~/.kube/config
      ansible.builtin.shell: |
        k3s kubectl config view --raw >> /root/.kube/config
        exit 0
      args:
        creates: /root/.kube/config
    - name: add KUBECONFIG to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "KUBECONFIG=/root/.kube/config"
    - name: create helm directory
      ansible.builtin.file:
        path: /root/helm
        state: directory
    - name: download get_helm.sh
      ansible.builtin.shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      args:
        chdir: /root/helm
        creates: get_helm.sh
    - name: make get_helm.sh executable
      ansible.builtin.file:
        path: /root/helm/get_helm.sh
        owner: root
        group: root
        mode: u+rwx
        state: file
    - name: install helm
      ansible.builtin.shell: |
        ./get_helm.sh >> /tmp/helm.log
        exit 0
      args:
        chdir: /root/helm
        creates: /tmp/helm.log
    - name: install arcade
      ansible.builtin.shell: |
        curl -sLS https://get.arkade.dev | sudo sh >> arcade.log
        exit 0
      args:
        creates: /tmp/arcade.log