- name: Storage Node
  hosts: storage_nodes
  tasks:
    - name: create ext4 filesystem on /dev/sba
      ansible.builtin.filesystem:
        fstype: ext4
        dev: /dev/sda
    - name: create /data directory
      ansible.builtin.file:
        path: /data
        state: directory
    - name: define mounts in fstab 
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "/dev/sda /data ext4 defaults 0 0"
    - name: mount /dev/sda in /data
      ansible.builtin.shell: |
        mount -a >> /tmp/mount.log
        exit 0
      args:
        creates: /tmp/mount.log